// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvpsowixytpefhwagoxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2cHNvd2l4eXRwZWZod2Fnb3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzAzNjksImV4cCI6MjA2NTU0NjM2OX0.IVtYcflZ03oW1b9hAcnXcEE4kNUsSJstBBp7TPEFsgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);